// src/pages/yatv/_favorites.svelte
<script>
  import Container from "../../components/Content/Container.svelte";
  import Item from "../../components/yatv/Content/Item.svelte";
  import { PersistentStore } from "../../libs/source/twitter";
  import { YatvProvider } from "../../libs/source/yatv";

  const provider = new YatvProvider();

  const favorite = provider.favorite.use("svelte");

  async function migrate() {
    const old = new PersistentStore("yatv", null);
    const data = await Promise.all(
      old.export().map((v) => provider.getVideo(v))
    );
    console.log(data);
    if (provider.favorite.Type === "object") {
      console.log("object");
      await provider.favorite.import(data);
      console.log("imported");
    }
  }
</script>

<div class="wrapper">
  <button on:click={() => migrate()}>Migrate</button>
  <Container>
    {#each $favorite as v (v.id)}
      <Item videoInfo={v} />
    {/each}
  </Container>
</div>

// src/pages/twitter/[site]/_favorites.tsx
import styled from "styled-components";
import Content from "../../../components/twitter/Content";
import { Providers } from "../../../libs/source";
import { useMemo } from "react";
import { PersistentStore } from "../../../libs/source/twitter";

interface Props {
  provider: keyof typeof Providers;
}

export default function Index(props: Props) {
  const provider = useMemo(() => new Providers[props.provider](), []);
  const favorite = provider.favorite.use("react");

  const migrate = async () => {
    const old = new PersistentStore("twivideo");
    const data = (await Promise.all(old.export().map((v) => provider.getVideo(v))));
    console.log(data);
    if (provider.favorite.Type === "object") {
      console.log("object");
      await provider.favorite.import(data);
      console.log("imported");
    }
  }

  return (
    <>
      <Wrapper>
        <button onClick={() => migrate()}>Migrate</button>
        <Content.Container>
          {favorite.map((v, i) => (
            <Content.Item
              provider={provider}
              key={typeof v === "string" ? v : v.id}
              detail={typeof v === "string" ? provider.getVideo(v) : v}
            />
          ))}
        </Content.Container>
      </Wrapper>
    </>
  );
}

const Wrapper = styled.div`
  width: 100%;
  height: 100%;

  padding-top: 20px;
  margin-bottom: 20px;
`;
