// src/pages/hitomi/_index.tsx
import styled from "styled-components";
import { useCallback, useEffect, useRef, useState } from "react";
import useIntersectionObserver from "../../libs/observer";
import { Hitomi } from "../../libs/api";
import Content from "../../components/hitomi/Content";

export default function Index() {
  const [search, setSearch] = useState<string>("");

  const [indexes, setIndexes] = useState<number[]>([]);
  const [page, setPage] = useState<number>(1);
  const [observe, unobserve] = useIntersectionObserver(
    () => setPage((page) => page + 1),
    {
      threshold: 1,
    }
  );

  const fetch = useCallback(
    async (search: string | null, page: number, indexes: number[]) =>
      new Promise((resolve) => {
        if (search) {
          Hitomi.getSearch(search, page).then((res) => {
            setIndexes(indexes.concat(res));
            resolve(indexes.concat(res));
          });
        } else {
          Hitomi.getIndexes(page).then((res) => {
            setIndexes(indexes.concat(res));
            resolve(indexes.concat(res));
          });
        }
      }),
    []
  );

  const target = useRef(null);
  const prevSearch = useRef<string | null>(null);
  const loading = useRef<boolean>(true);

  useEffect(() => {
    const targetNode = target.current;
    if (targetNode) observe(targetNode);
    return () => {
      if (targetNode) unobserve(targetNode);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    setSearch(params.get("search") ?? "");
  }, []);

  useEffect(() => {
    if (prevSearch.current !== search) {
      setPage(1);
      prevSearch.current = search;
      fetch(search, 1, []).then(() => {
        console.log("fetch");
        loading.current = false;
      });
    } else {
      fetch(search, page, indexes).then(() => {
        console.log("fetch");
        loading.current = false;
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, search]);

  return (
    <>
      <Wrapper>
        <Content.Container>
          {loading.current
            ? [...Array(20)].map((_, i) => <Content.Skeleton key={i} />)
            : indexes.map((v, i) => (
                <Content.Item key={i} index={v.toString()} />
              ))}
          <Intersection
            id="intersection"
            ref={target}
            $visible={indexes.length > 0}
          >
            Loading...
          </Intersection>
        </Content.Container>
      </Wrapper>
    </>
  );
}

const Wrapper = styled.div`
  width: 100%;
  height: 100%;

  padding-top: 20px;
  margin-bottom: 20px;
`;

const Intersection = styled.div<{
  $visible: boolean;
}>`
  width: 100%;
  height: 100px;
  text-align: center;
  display: ${(props) => (props.$visible ? "block" : "none")};
`;

// src/pages/lover/_index.svelte
<script lang="ts">
  import IntersectionObserver from "svelte-intersection-observer";
  import Common from "../../components/Content";
  import Item from "../../components/lover/Content/Item.svelte";
  import { Lover } from "../../libs/api";

  let loading = true;
  let observed = false;
  let page = 1;
  let videos: Lover.SearchResultVideo[] = [];
  let element: HTMLDivElement;

  async function fetch(page: number) {
    const { videos: data } = await Lover.getIndex(page);
    videos = videos.concat(data);
  }

  $: {
    fetch(page).then(() => {
      loading = false;
      observed = false;
    });
  }
</script>

<div class="wrapper">
  <Common.Container>
    {#if loading}
      {#each Array(10) as _}
        <Common.Skeleton />
      {/each}
    {:else}
      {#each videos as video, i}
        <Item videoId={video.id} />
      {/each}
    {/if}
    <IntersectionObserver
      {element}
      on:intersect={() => {
        if (!observed) {
          observed = true;
          page++;
        }
      }}
    >
      <div bind:this={element} data-visible={videos.length > 0}>Loading...</div>
    </IntersectionObserver>
  </Common.Container>
</div>

<style lang="scss">
  .wrapper {
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;

    div {
      &[data-visible="true"] {
        display: block;
      }
      &[data-visible="false"] {
        display: none;
      }
    }
  }
</style>
