// src/components/lover/Modal/Detail.tsx
import { styled } from "styled-components";
import { useEffect, useRef, useState } from "react";
import Modal from "../../Modal";
import Favorite from "../Content/Favorite";
import type { VideoInfo } from "../../../libs/api/lover";
import { $setting as $twitter } from "../../../store/twitter/setting";
import { $setting as $common } from "../../../store/setting";
import { translateVideoURL } from "../../../scripts/thumbnail";
import Hls from "hls.js";

type Props = {
  close: () => void;
  id: string;
  detail: VideoInfo;
};

export default function Detail({ close, id, detail }: Props) {
  const [censored, setCensored] = useState<boolean>();
  const [autoPlay, setAutoPlay] = useState<boolean>($twitter.get().autoPlay);
  const [loop, setLoop] = useState<boolean>($twitter.get().loop);

  const videoRef = useRef<HTMLVideoElement>(null);

  $common.listen((setting) => {
    setCensored(setting.censored);
  });
  $twitter.listen((setting) => {
    setAutoPlay(setting.autoPlay);
    setLoop(setting.loop);
  });

  useEffect(() => {
    if (!censored && Hls.isSupported() && videoRef.current) {
      const hls = new Hls({
        maxBufferLength: 60 * 60,
      });
      hls.loadSource(translateVideoURL(detail.video));
      hls.attachMedia(videoRef.current);
    }
  }, []);

  return (
    <>
      <Modal.Default maxWidth={1200} close={close}>
        <Wrapper>
          <Video
            ref={videoRef}
            controls
            autoFocus
            loop={loop}
            autoPlay={autoPlay}
          >
            {censored && (
              <source src="https://youtu.be/0bIRwBpBcZQ" type="video/mp4" />
            )}
          </Video>
          <TopRow>
            <Menu>
              <Favorite videoId={id} />
            </Menu>
          </TopRow>
          <ExternalLink href={detail.webpage_url} target="_blank">
            <Title>
              {censored ? detail.title ?? "\u00a0" : "Good Picture 👍"}
            </Title>
          </ExternalLink>
        </Wrapper>
      </Modal.Default>
    </>
  );
}

const Wrapper = styled.div`
  width: 100%;
  height: 100%;

  display: flex;
  flex-direction: column;
  gap: 10px;
`;

const Video = styled.video`
  width: 100%;
  height: 100%;
  aspect-ratio: 16 / 9;
`;

const TopRow = styled.div`
  width: 100%;

  display: flex;
  flex-direction: row;
  justify-content: space-between;
`;

const Menu = styled.div`
  display: flex;
  flex-direction: row;
  gap: 10px;
`;

const User = styled.h1`
  font-size: 24px;
  font-weight: 600;
  color: white;
`;

const Title = styled.h2`
  font-size: 24px;
  font-weight: 500;
  color: white;
  white-space: pre-wrap;

  @media screen and (max-width: 768px) {
    font-size: 18px;
  }
`;

const ExternalLink = styled.a``;

// src/components/yatv/Modal/Detail.svelte
<script lang="ts">
  import { setting as common } from "../../../store/setting";
  import { setting as twitter } from "../../../store/twitter/setting";
  import Default from "../../Modal/Default.svelte";
  import Hls from "hls.js";
  import { Yatv } from "../../../libs/api";

  let videoRef: HTMLVideoElement;

  export let close: () => void;
  export let info: Yatv.SearchResultVideo;

  let detail: Yatv.VideoInfo | null = null;

  Yatv.getVideo(info.url).then((res) => {
    detail = res;
  });

  console.log(detail);

  $: if (videoRef && detail) {
    if (!$common.censored && Hls.isSupported()) {
      const hls = new Hls({
        maxBufferLength: 60 * 2,
        xhrSetup(xhr, url) {
          xhr.open("POST", Yatv.MIRROR_URL, true);
          xhr.setRequestHeader("Content-Type", "application/json");
          xhr.send(
            JSON.stringify({
              url,
            })
          );
          xhr.send = () => {};
        },
      });
      hls.loadSource(detail.video);
      hls.attachMedia(videoRef);
      videoRef.focus();
    } else {
      videoRef.src =
        "https://file-examples.com/storage/fe7e31ec4b64ff77da87142/2017/04/file_example_MP4_480_1_5MG.mp4";
    }
  }
</script>

<Default maxWidth={1200} {close}>
  <div class="wrapper">
    <video
      bind:this={videoRef}
      controls
      loop={$twitter.loop}
      autoplay={$twitter.autoPlay}
    >
      <track kind="captions" />
    </video>
    <div class="top-row">
      <div class="menu">
        <!-- <Favorite videoId={info.url} /> -->
      </div>
    </div>
    <a href="/test" class="external-link">
      <h2 class="title">
        {$common.censored ? "Good Picture 👍" : info.title ?? "\u00a0"}
      </h2>
    </a>
  </div>
</Default>

<style lang="scss">
  .wrapper {
    width: 100%;
    height: 100%;

    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  video {
    width: 100%;
    height: 100%;
    aspect-ratio: 16 / 9;
  }

  .top-row {
    width: 100%;

    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }

  .menu {
    display: flex;
    flex-direction: row;
    gap: 10px;
  }

  h2 {
    font-size: 24px;
    font-weight: 500;
    color: white;
    white-space: pre-wrap;

    @media screen and (max-width: 768px) {
      font-size: 18px;
    }
  }
</style>
