// src/pages/lover/_favorites.svelte
<script>
  import Container from "../../components/Content/Container.svelte";
  import Item from "../../components/lover/Content/Item.svelte";
  import { favorite } from "../../store/lover/favorite";
</script>

<div class="wrapper">
  <Container>
    {#each $favorite as v, i}
      <Item videoId={v} />
    {/each}
  </Container>
</div>

// src/pages/twitter/favorites.tsx
import { useStore } from "@nanostores/react";
import styled from "styled-components";
import { $favorite } from "../../store/twitter/favorite";
import Content from "../../components/twitter/Content";

export default function Index() {
  const favorite = useStore($favorite);

  return (
    <>
      <Wrapper>
        <Content.Container>
          {favorite &&
            favorite.map((v, i) => <Content.Item key={i} videoId={v} />)}
        </Content.Container>
      </Wrapper>
    </>
  );
}

const Wrapper = styled.div`
  width: 100%;
  height: 100%;

  padding-top: 20px;
  margin-bottom: 20px;
`;
